module.exports = {
  users: [
    {username: 'Chee', email: 'chee@zv.sg', password: 'pass1234'},
    {username: 'Zhi', email: 'zhi@zv.sg', password: 'pass1234'},
    {username: 'Qu', email: 'qu@zv.sg', password: 'pass1234'},
    {username: 'Lu', email: 'lu@zv.sg', password: 'pass1234'},
    {username: 'Ah', email: 'ah@zv.sg', password: 'pass1234'},
    {username: 'Badoo', email: 'badoo@zv.sg', password: 'pass1234'},
    {username: 'Booza', email: 'booza@zv.sg', password: 'pass1234'},
    {username: 'Pro', email: 'pro@zv.sg', password: 'pass1234'}
  ],
  companies: [
    {title: 'Apple'},
    {title: 'Procter and Gamble'},
    {title: 'Samsung'},
    {title: 'DBS'},
    {title: 'Ernest and Young'},
    {title: 'Hewlett Packard'},
    {title: 'PricewaterhouseCoopers'},
    {title: 'KPMG'},
    {title: 'Google'},
    {title: 'Microsoft'},
    {title: 'Mediacorp'},
    {title: 'BBDO'},
    {title: 'ApiCarnival'},
    {title: 'SaladBroker'}
  ],
  designations: [
    {title: 'Software Engineer'},
    {title: 'Business Developer'},
    {title: 'Accountant'},
    {title: 'Electrical Engineer'},
    {title: 'Senior Software Engineer'},
    {title: 'Technical Lead'},
    {title: 'Senior Accountant'},
    {title: 'Associate Consultant'},
    {title: 'Consultant'},
    {title: 'Manager'},
    {title: 'Director'},
    {title: 'Chief Executive Officer'},
    {title: 'Chief Technology Officer'},
    {title: 'Chief Operation Officer'},
    {title: 'Chief Finance Officer'},
    {title: 'Intern'},
    {title: 'Senior Associate'},
    {title: 'Associate'},
    {title: 'HR Manager'},
    {title: 'Auditor'},
  ],
  industries: [
    {title: 'Oil and Gas'},
    {title: 'Accounting'},
    {title: 'Financial Services'},
    {title: 'Management Consulting'},
    {title: 'Information Technology'},
    {title: 'Legal Services'},
    {title: 'Advertising'},
    {title: 'Software'},
    {title: 'Aerospace'},
    {title: 'Banking'},
    {title: 'Real Estate'},
    {title: 'Consumer Products'},
  ],
  profiles: [
    {name: "Jassie Lee", designation: 18, industry: 2, company: 7, user: 1},
    {name: "Jun Yung", designation: 3, industry: 12, company: 2, user: 2},
    {name: "Peter Marker", designation: 12, industry: 5, company: 14, user: 3},
    {name: "Michael Strongman", designation:1, industry: 5, company: 9, user: 4},
    {name: "Chen Li", designation: 4, industry: 8, company:13, user: 5},
    {name: "Ben Shek", designation: 4, industry: 9, company:13, user: 6},
    {name: "Paul Frank", designation: 7, industry: 5, company: 9, user: 7},
    {name: "Pro Ka Kee", designation: 6, industry: 5, company: 2, user: 8},
  ],
  passports: [
    {protocol: 'local', password: 'pass1234', user: 1},
    {protocol: 'local', password: 'pass1234', user: 2},
    {protocol: 'local', password: 'pass1234', user: 3},
    {protocol: 'local', password: 'pass1234', user: 4},
    {protocol: 'local', password: 'pass1234', user: 5},
    {protocol: 'local', password: 'pass1234', user: 6},
    {protocol: 'local', password: 'pass1234', user: 7},
    {protocol: 'local', password: 'pass1234', user: 8},
  ],
  devices: [
    {deviceId: "54ff70066667515122581267", tagId: "1792429212", user: 2},
    {deviceId: "54ff70066672524845491867", tagId: "2277639212", user: 3}
  ],
}
